# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('band_members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band_member',
            name='img',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
